### ISSUE TITLE
так много вопросов, так мало ответов

### ISSUE THREAD

**Issue by nadya-t** [yualapshina/registration-system-coursework#64]
1. настоящий деплой (вышкинские сервера???)
2. форма технической документации
3. согласие на обработку персональных данных
4. показывать ли мероприятия, которые прошли и регистрация на которые закрыта?
5. мб есть какой-то актуальный шаблон сертификата которым часто пользуются.. вдруг?
6. когда нам прислать тексты почитать? и возможно обсудить структурно что важно-неважно включить
7. процесс сдачи отзывов-рецензий - даты, как нам кидать рецензенту и т.д.
8. нужно ли срочно еще что-то менять в системе или оставляем как есть
9. как в работе ссылаться на всякие ресурсы, помимо кода (требования, фигма, документы тестирования)? можно в приложения ссылку+QR? как-то еще?
10. обязательно ли делать презентацию по шаблону вшэ, или можно просто в стилистике вшэ? я могу пример показать..
11. личные местоимения
12. что конкретно должно быть в 7 минутах защиты. что важно, что лучше опустить, как демонстрировать систему в этот срок

**Comment by yualapshina** [comment]
1. деплой какой-то будет, необходимо много работать с айтишниками. в текст вписываем историю тестового деплоя
2. можно вики, можно ссылку в работу.
3. документы (два согласия) будут скинуты, нужно передвинуть, скорее всего в регистрацию. 
4. старые не нужны
5. старый шаблон пришлют, но может часто меняться
6. всё в целом готово
7. полностью готовый текст загрузить в лмс + отправить на отзыв и рецензию. после получения отзыва и рецензии отправить их в учебный офис. всё это распечатанное притаранить на защиту
8. всё норм, доделать все планируемые мелочи
9. большие схемы: кусочек в текст, ссылку и кьюар в приложение. спецификация: целиком в приложение
10. по шаблону не обязательно, можно условно в свободном стиле
11. писать лучше в безличной форме
12. лучше видеоролик. рассказать: постановка задачи, как решали, результат
